# Generated by Django 3.2.25 on 2024-05-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_series_image_url'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product_access',
            field=models.ManyToManyField(blank=True, related_name='product_user', to='products.Product'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='series_access',
            field=models.ManyToManyField(blank=True, related_name='series_user', to='products.Series'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_access',
            field=models.ManyToManyField(blank=True, related_name='token_user', to='products.CoachingToken'),
        ),
    ]
