# Generated by Django 3.2.25 on 2024-05-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_series_image_url'),
        ('profiles', '0002_auto_20240508_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='token_access',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='product_access',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_user', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='series_access',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_user', to='products.Series'),
        ),
    ]
