# Generated by Django 3.2.25 on 2024-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_series_image_url'),
        ('profiles', '0003_auto_20240510_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='product_access',
            field=models.ManyToManyField(blank=True, related_name='product_user', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='series_access',
            field=models.ManyToManyField(blank=True, related_name='series_user', to='products.Series'),
        ),
    ]
