# Generated by Django 3.2.25 on 2024-05-12 22:53

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240511_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='Order',
            name='street_address1',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='Order',
            name='street_address2',
            field=models.CharField(max_length=80, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='Order',
            name='town_or_city',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='Order',
            name='county',
            field=models.CharField(max_length=80, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='Order',
            name='postcode',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='Order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
