# Generated by Django 3.2.25 on 2024-05-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20240512_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='Order',
            name='delivery_cost',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6
            )
        ),
    ]
