# Generated by Django 3.2.25 on 2024-05-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
