# Generated by Django 3.2.25 on 2024-04-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.PositiveIntegerField(default=20, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='uploads/'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(
                    blank=True,
                    max_length=254,
                    null=True
                )),
                ('series_no', models.PositiveIntegerField(
                    max_length=3,
                    unique=True
                )),
                ('category', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='products.category'
                )),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='series_no',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='products.series',
                verbose_name='Series Number'
            ),
        ),
    ]
