# Generated by Django 3.2.25 on 2024-04-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240423_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
