# Generated by Django 3.2.25 on 2024-04-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240429_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.CharField(blank=True, default='20 minutes', max_length=254, null=True),
        ),
    ]
