# Generated by Django 3.2.25 on 2024-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
