# Generated by Django 3.2.25 on 2024-05-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_series_screenshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
    ]
