# Generated by Django 3.2.25 on 2024-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_series_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='price',
            field=models.DecimalField(
                decimal_places=2,
                default=34.99,
                max_digits=6
            ),
        ),
    ]
