# Generated by Django 3.2.25 on 2024-05-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20240503_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
