# Generated by Django 3.2.25 on 2024-05-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_series_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingtoken',
            name='session',
        ),
        migrations.RemoveField(
            model_name='coachingtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='CoachingSession',
        ),
        migrations.DeleteModel(
            name='CoachingToken',
        ),
    ]
