# Generated by Django 3.2.25 on 2024-05-15 20:40

from django.db import migrations, models
import urllib.request
from django.core.files import File
import os

def copy_urls_to_files(apps, schema_editor):
    Series = apps.get_model('products', 'Series')
    for series in Series.objects.all():
        if series.video_url:
            result = urllib.request.urlretrieve(series.video_url)
            series.video.save(
                os.path.basename(series.video_url),
                File(open(result[0], 'rb'))
            )
        if series.screenshot:
            result = urllib.request.urlretrieve(series.screenshot)
            series.screenshot_1.save(
                os.path.basename(series.screenshot),
                File(open(result[0], 'rb'))
            )
        if series.image_url:
            result = urllib.request.urlretrieve(series.image_url)
            series.image.save(
                os.path.basename(series.image_url),
                File(open(result[0], 'rb'))
            )
        series.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20240515_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='series_images/'),
        ),
        migrations.AddField(
            model_name='series',
            name='screenshot_1',
            field=models.ImageField(blank=True, null=True, upload_to='series_screenshots/'),
        ),
        migrations.AddField(
            model_name='series',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='series_videos/'),
        ),
        migrations.RunPython(copy_urls_to_files),
    ]
