# Generated by Django 3.2.25 on 2024-05-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20240515_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='series',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='series',
            name='video_url',
        ),
    ]
